import os
import re
import json
from datetime import datetime, timedelta

# Konfigurasi
ASSETS_DIR = r"c:\Users\denis\Documents\GitHub\studyo_music_library\assets\sounds"
LIB_CORE_DIR = r"c:\Users\denis\Documents\GitHub\studyo_music_library\lib\core\sound_manager\core"
MANAGER_DIR = r"c:\Users\denis\Documents\GitHub\studyo_music_library\lib\core\sound_manager\manager"
ENUMS_FILE = os.path.join(LIB_CORE_DIR, "sound_enums.dart")
PATHS_FILE = os.path.join(LIB_CORE_DIR, "sound_paths.dart")
BGM_MANAGER_FILE = os.path.join(MANAGER_DIR, "bgm_manager.dart")
PUBSPEC_FILE = r"c:\Users\denis\Documents\GitHub\studyo_music_library\pubspec.yaml"
MANIFEST_FILE = os.path.join(ASSETS_DIR, "sound_manifest.json")
OVERVIEW_FILE = r"c:\Users\denis\Documents\GitHub\studyo_music_library\quick_overview_used_new_assets.txt"

# Header file Dart
HEADER = """/// GENERATED CODE - DO NOT MODIFY BY HAND
/// This file is generated by generate_sound_code.py
///
/// To regenerate, run: python generate_sound_code.py
"""

def to_camel_case(snake_str):
    """Convert snake_case to camelCase"""
    components = snake_str.split('_')
    return components[0] + ''.join(x.title() for x in components[1:])

def to_pascal_case(snake_str):
    """Convert snake_case to PascalCase"""
    components = snake_str.split('_')
    return ''.join(x.title() for x in components)

def clean_name(name):
    """Membersihkan nama file agar valid jadi identifier Dart"""
    name = os.path.splitext(name)[0]  # Hapus ekstensi
    name = re.sub(r'[^a-zA-Z0-9_]', '_', name)  # Ganti symbol jadi underscore
    if name[0].isdigit(): name = 'sound_' + name
    return to_camel_case(name)

def update_pubspec(categories):
    print(f"Checking pubspec.yaml...")
    if not os.path.exists(PUBSPEC_FILE):
        print("Error: pubspec.yaml not found!")
        return

    # Use UTF-8 explicitly
    with open(PUBSPEC_FILE, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    new_lines = []
    assets_section_found = False
    flutter_section_found = False
    existing_assets = set()
    asset_insert_index = -1
    
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped == 'flutter:':
            flutter_section_found = True
        elif stripped == 'assets:' and flutter_section_found:
            assets_section_found = True
            asset_insert_index = i + 1
        elif assets_section_found:
            if not line.startswith('  ') and stripped != '':
                 assets_section_found = False
            else:
                if stripped.startswith('- assets/sounds/'):
                    path = stripped.replace('-', '').strip().strip('/')
                    cat = os.path.basename(path)
                    existing_assets.add(cat)
        new_lines.append(line)

    missing_cats = [c for c in categories if c not in existing_assets]
    if missing_cats and asset_insert_index != -1:
        print(f"  Adding {len(missing_cats)} missing categories to pubspec.")
        for cat in missing_cats:
            print(f"    + {cat}")
            new_lines.insert(asset_insert_index, f"    - assets/sounds/{cat}/\n")
        
        with open(PUBSPEC_FILE, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)
        print("Updated pubspec.yaml successfully.")

def update_sound_type_enum(categories):
    print("Checking SoundType enum in bgm_manager.dart...")
    if not os.path.exists(BGM_MANAGER_FILE):
        print("Error: bgm_manager.dart not found!")
        return

    with open(BGM_MANAGER_FILE, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find Enum block
    pattern = r"enum\s+SoundType\s*\{([^}]+)\}"
    match = re.search(pattern, content)
    if not match:
        print("Error: Could not find 'enum SoundType' in bgm_manager.dart")
        return

    existing_block = match.group(1)
    existing_types = [x.strip().replace(',', '') for x in existing_block.split('\n') if x.strip()]
    
    # Check what's missing
    missing_types = []
    for cat in categories:
        type_name = to_camel_case(cat)
        if type_name not in existing_types:
            missing_types.append(type_name)
            
    if not missing_types:
        return

    print(f"  Adding {len(missing_types)} missing types to SoundType enum.")
    
    # Insert new types before the closing brace
    # We reconstruct the enum block carefully
    
    insertion = "\n"
    for t in missing_types:
        print(f"    + {t}")
        insertion += f"  {t},\n"
    
    # Replace the closing brace with insertion + closing brace
    
    end_index = match.end(1) # End of content inside braces
    
    new_content = content[:end_index] + insertion + content[end_index:]
    
    with open(BGM_MANAGER_FILE, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print("Updated SoundType enum successfully.")

def generate_overview_file(structure, manifest):
    print(f"Generating overview file: {OVERVIEW_FILE}")
    
    new_assets = []
    now = datetime.now()
    threshold = timedelta(hours=24) # Show assets from last 24h as "New"
    
    # Alternative: Show all assets that were added to manifest in this run.
    # But for robustness, we use timestamp from manifest.

    for category, files in structure.items():
        for file in files:
            rel_path = f"{category}/{file}"
            date_str = manifest.get(rel_path, "")
            is_new = False
            if date_str:
                try:
                    date = datetime.fromisoformat(date_str)
                    if now - date < threshold:
                        is_new = True
                except: pass
            
            if is_new:
                new_assets.append({
                    'category': category,
                    'file': file,
                    'path': rel_path,
                    'date': date_str
                })
    
    with open(OVERVIEW_FILE, 'w', encoding='utf-8') as f:
        f.write("=================================================================\n")
        f.write("          QUICK OVERVIEW: NEW ASSETS (Last 24h)\n")
        f.write("=================================================================\n\n")
        
        if not new_assets:
            f.write("No new assets detected in the last 24 hours.\n")
            return

        f.write(f"Total New Assets: {len(new_assets)}\n\n")
        
        current_cat = ""
        for asset in new_assets:
            cat = asset['category']
            fname = clean_name(asset['file'])
            enum_class = "SoundTAP" if cat == "tap" else f"Sound{to_pascal_case(cat)}"
            type_enum = to_camel_case(cat)
            
            if cat != current_cat:
                f.write(f"\n--- {cat.upper()} ---\n")
                current_cat = cat
            
            f.write(f"File  : {asset['path']}\n")
            f.write(f"Code  :\n")
            f.write(f"await SoundController.instance.playSound(\n")
            f.write(f"  {enum_class}.{fname},\n")
            f.write(f"  SoundType.{type_enum},\n")
            f.write(f");\n")
            f.write("-" * 40 + "\n")

    print(f"Overview file updated with {len(new_assets)} new snippets.")

def generate_code():
    print(f"Scanning directory: {ASSETS_DIR}")

    # Load Manifest
    manifest = {}
    if os.path.exists(MANIFEST_FILE):
        try:
            with open(MANIFEST_FILE, 'r', encoding='utf-8') as f:
                manifest = json.load(f)
        except: pass

    structure = {}
    new_manifest_entries = False

    if not os.path.exists(ASSETS_DIR):
        print(f"Error: Directory {ASSETS_DIR} not found!")
        return

    categories = [d for d in os.listdir(ASSETS_DIR) if os.path.isdir(os.path.join(ASSETS_DIR, d))]
    categories.sort()
    
    # 1. Update Pubspec (Flutter Assets)
    update_pubspec(categories)
    
    # 2. Update SoundType Enum (Dart Logic)
    update_sound_type_enum(categories)

    for category in categories:
        cat_path = os.path.join(ASSETS_DIR, category)
        files = [f for f in os.listdir(cat_path) if f.lower().endswith('.m4a')]
        files.sort()

        if files:
            structure[category] = files
            for file in files:
                rel_path = f"{category}/{file}"
                if rel_path not in manifest:
                    manifest[rel_path] = datetime.now().isoformat()
                    new_manifest_entries = True
                    print(f"  [New Asset Detected]: {rel_path}")

    if new_manifest_entries:
        with open(MANIFEST_FILE, 'w', encoding='utf-8') as f:
            json.dump(manifest, f, indent=2)

    # 3. Generate sound_enums.dart
    print(f"Generating {ENUMS_FILE}...")
    with open(ENUMS_FILE, 'w', encoding='utf-8') as f:
        f.write(HEADER + "\n")
        for category, files in structure.items():
            enum_name = "SoundTAP" if category == 'tap' else f"Sound{to_pascal_case(category)}"
            f.write(f"/// Enum for {category} sounds\nenum {enum_name} {{\n")
            seen = set()
            for file in files:
                identifier = clean_name(file)
                if identifier in seen:
                    i = 2
                    while f"{identifier}{i}" in seen: i += 1
                    identifier = f"{identifier}{i}"
                seen.add(identifier)
                f.write(f"  {identifier},\n")
            f.write("}\n\n")

        f.write("/// Sound category selector\nenum SoundCategory {\n")
        for category in structure.keys():
            f.write(f"  {to_camel_case(category)},\n")
        if 'other' not in structure: f.write("  other,\n")
        f.write("}\n")

    # 4. Generate sound_paths.dart
    print(f"Generating {PATHS_FILE}...")
    with open(PATHS_FILE, 'w', encoding='utf-8') as f:
        f.write(HEADER)
        f.write("import 'sound_enums.dart';\n\n")
        f.write("class SoundPaths {\n  SoundPaths._();\n  static final instance = SoundPaths._();\n")
        f.write("  static const _root = 'packages/studyo_music_library/assets/sounds/';\n\n")

        for category, files in structure.items():
            enum_name = "SoundTAP" if category == 'tap' else f"Sound{to_pascal_case(category)}"
            map_name = f"{category}SoundPaths"
            f.write(f"  final {map_name} = <{enum_name}, String>{{\n")
            seen = set()
            for file in files:
                identifier = clean_name(file)
                if identifier in seen:
                    i = 2
                    while f"{identifier}{i}" in seen: i += 1
                    identifier = f"{identifier}{i}"
                seen.add(identifier)
                f.write(f"    {enum_name}.{identifier}: '${{_root}}{category}/{file}',\n")
            f.write("  };\n\n")

        f.write("  final Map<String, String> _creationDates = {\n")
        for category, files in structure.items():
            for file in files:
                 rel_path = f"{category}/{file}"
                 date_str = manifest.get(rel_path, "")
                 f.write(f"    '${{_root}}{category}/{file}': '{date_str}',\n")
        f.write("  };\n\n")
        
        f.write("  DateTime? getCreationDate(String assetPath) => DateTime.tryParse(_creationDates[assetPath] ?? '');\n\n")

        f.write("  String? getSoundPath(SoundCategory cat, dynamic sound) {\n    switch (cat) {\n")
        for category in structure.keys():
            cat_enum = to_camel_case(category)
            map_name = f"{category}SoundPaths"
            f.write(f"      case SoundCategory.{cat_enum}: return {map_name}[sound];\n")
        if 'other' not in structure:
            f.write("      case SoundCategory.other: return otherSoundPaths[sound];\n")
        f.write("    }\n  }\n\n")

        f.write("  List<String> getAllSoundPaths() => [ for (final map in allSoundMaps.values) ...map.values ];\n\n")
        f.write("  Map<SoundCategory, Map<dynamic, String>> get allSoundMaps => {\n")
        for category in structure.keys():
             cat_enum = to_camel_case(category)
             map_name = f"{category}SoundPaths"
             f.write(f"        SoundCategory.{cat_enum}: {map_name},\n")
        f.write("      };\n}\n")

    # 5. Generate Overview Text File
    generate_overview_file(structure, manifest)

    print("Done! All Code & Overview Generated.")

if __name__ == "__main__":
    generate_code()
